<<<<<<< HEAD
export default {
=======
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
>>>>>>> 8fb54b05b7c51bcdac0e17d25cd9deb8136500a4
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
